version: '3.8'

services:
  dask-scheduler:
    image: daskdev/dask:latest
    container_name: dask-scheduler
    command: dask-scheduler
    ports:
      - "8786:8786"
      - "8787:8787"
    networks:
      - dask-network
    restart: always

networks:
  dask-network:
    driver: bridge
