version: '3.8'
services:
  scheduler:
    image: daskdev/dask:latest
    container_name: dask_scheduler
    ports:
      - "8786:8786"  
      - "8787:8787"  
    networks:
      - dask-network
networks:
  dask-network:
    driver: bridge
